[build]
builder = "nixpacks"

[deploy]
startCommand = "npx prisma migrate deploy && PORT=8080 node server.mjs"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
numReplicas = 1
